import arrayToTable from './arrayToTable';
import BitField from './BitField';
import Bytes from './Byte';
import capitalize from './capitalize';
import { addButtonsByRoles, addButtonsToRows, addOptionsToSelectMenuInRow, addSelectMenuByRoles, calculateBitFieldFromSelectMenus, ComponentLink, componentsHasRoles, createButtonsByRoles, createSelectMenuByRoles, createSelectMenuFromOptions, filterRolesId, getAppOwners, getDefaultOptionFromSelectMenu, getLocalizations, removeButtonsById, removeButtonsByRoleId, removeOptionsByRolesFromSelectMenu, removeOptionsFromSelectMenu, reorganizeButtons, reorganizeOptionsByDefaultInSelectMenu, setBitFieldValuesOnSelectMenus, setDefaultRole } from './commands';
import composition from './composition';
import Constants from './Constants';
import djsLimits from './djsLimits';
import { EmbedHelper } from './EmbedHelper';
import Emoji from './Emoji';
import filterObjectByKeys from './filterObjectByKeys';
import findDuplicatesInArray from './findDuplicatesInArray';
import getRandomFromArray from './getRandomFromArray';
import hasDuplicatesInArray from './hasDuplicatesInArray';
import isClass from './isClass';
import isDuplicate from './isDuplicate';
import isJSON from './isJSON';
import isSameDate from './isSameDate';
import JSONparse from './JSONparse';
import keyGen from './keyGen';
import limitArrayByStringLength from './limitArrayByStringLength';
import { formatLocale, Locales } from './Locales';
import mathRandom from './mathRandom';
import objectToTable from './objectToTable';
import randomizeArray from './randomizeArray';
import { RecursivelyReadDirSync } from './RecursivelyReadDirSync';
import regexp from './regexp';
import removeDuplicatesInArray from './removeDuplicatesInArray';
import removeFromArray from './removeFromArray';
import splitArrayInGroups from './splitArrayInGroups';
import splitLimits from './splitLimits';
import toSnakeCase, { snakeCase } from './toSnakeCase';
import waitAsync from './waitAsync';
import waitSync from './waitSync';

export default abstract class Util {
  static arrayToTable = arrayToTable;
  static BitField = BitField;
  static Bytes = Bytes;
  static capitalize = capitalize;
  static composition = composition;
  static Constants = Constants;
  static djsLimits = djsLimits;
  static EmbedHelper = EmbedHelper;
  static Emoji = Emoji;
  static filterObjectByKeys = filterObjectByKeys;
  static findDuplicatesInArray = findDuplicatesInArray;
  static formatLocale = formatLocale;
  static getRandomFromArray = getRandomFromArray;
  static hasDuplicatesInArray = hasDuplicatesInArray;
  static isClass = isClass;
  static isDuplicate = isDuplicate;
  static isJSON = isJSON;
  static isSameDate = isSameDate;
  static JSONparse = JSONparse;
  static keyGen = keyGen;
  static limitArrayByStringLength = limitArrayByStringLength;
  static Locales = Locales;
  static mathRandom = mathRandom;
  static objectToTable = objectToTable;
  static regexp = regexp;
  static randomizeArray = randomizeArray;
  static RecursivelyReadDirSync = RecursivelyReadDirSync;
  static removeDuplicatesInArray = removeDuplicatesInArray;
  static removeFromArray = removeFromArray;
  static snakeCase = snakeCase;
  static splitArrayInGroups = splitArrayInGroups;
  static splitLimits = splitLimits;
  static toSnakeCase = toSnakeCase;
  static waitAsync = waitAsync;
  static waitSync = waitSync;

  // Commands utils
  static addButtonsByRoles = addButtonsByRoles;
  static addSelectMenuByRoles = addSelectMenuByRoles;
  static addOptionsToSelectMenuInRow = addOptionsToSelectMenuInRow;
  static addButtonsToRows = addButtonsToRows;
  static calculateBitFieldFromSelectMenus = calculateBitFieldFromSelectMenus;
  static ComponentLink = ComponentLink;
  static componentsHasRoles = componentsHasRoles;
  static createButtonsByRoles = createButtonsByRoles;
  static createSelectMenuFromOptions = createSelectMenuFromOptions;
  static createSelectMenuByRoles = createSelectMenuByRoles;
  static filterRolesId = filterRolesId;
  static getAppOwners = getAppOwners;
  static getDefaultOptionFromSelectMenu = getDefaultOptionFromSelectMenu;
  static getLocalizations = getLocalizations;
  static removeButtonsById = removeButtonsById;
  static removeButtonsByRoleId = removeButtonsByRoleId;
  static removeOptionsFromSelectMenu = removeOptionsFromSelectMenu;
  static removeOptionsByRolesFromSelectMenu = removeOptionsByRolesFromSelectMenu;
  static reorganizeButtons = reorganizeButtons;
  static reorganizeOptionsByDefaultInSelectMenu = reorganizeOptionsByDefaultInSelectMenu;
  static setBitFieldValuesOnSelectMenus = setBitFieldValuesOnSelectMenus;
  static setDefaultRole = setDefaultRole;
}

export { Util };

