name: Bug report
description: Create a report to help us improve
labels: [bug]

body:
  - type: markdown
    attributes:
      value: |
        Use Discord for questions: https://discord.gg/YCRyk39Tqt

  - type: textarea
    id: description
    validations:
      required: true
    attributes:
      label: Issue description
      description: |
        Describe the issue in as much detail as possible.

        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files into it.

  - type: textarea
    id: codeSample
    attributes:
      label: Code sample
      description: Include a reproducible, minimal code sample. This will be automatically formatted into code, so no need for backticks.
      render: TypeScript
      placeholder: |
        Your code sample should be...
        ... Minimal - Use as little code as possible that still produces the same problem (and is understandable)
        ... Complete - Provide all parts someone else needs to reproduce your problem
        ... Reproducible - Test the code you're about to provide to make sure it reproduces the problem

  - type: textarea
    id: additionalContext
    attributes:
      label: Additional context
      description: Add any other context about the problem here.
