module.exports = {
  bytes: require('./bytes'),
  capitalize: require('./capitalize'),
  filterObjectByKeys: require('./filterObjectByKeys'),
  findDuplicatesInArray: require('./findDuplicatesInArray'),
  hasDuplicatesInArray: require('./hasDuplicatesInArray'),
  isSameDate: require('./isSameDate'),
  isDuplicate: require('./isDuplicate'),
  isJSON: require('./isJSON'),
  jankenpon: require('./jankenpon'),
  keyGen: require('./keyGen'),
  mathRandom: require('./mathRandom'),
  parseJSON: require('./parseJSON'),
  regexp: require('./RegExp'),
  removeDuplicatesInArray: require('./removeDuplicatesInArray'),
  removeFromArray: require('./removeFromArray'),
  splitArrayInGroups: require('./splitArrayInGroups'),
  splitLimits: require('./splitLimits'),
  splitSelectMenu: require('./splitSelectMenu'),
  waitAsync: require('./waitAsyncV2'),
  waitSync: require('./waitSync'),
};